package com.appify.android.moneysaver

import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.view.View
import androidx.navigation.findNavController
import androidx.navigation.ui.setupWithNavController
import com.appify.android.moneysaver.databinding.ActivityMainBinding
import com.google.android.material.bottomnavigation.BottomNavigationView
import com.google.firebase.analytics.FirebaseAnalytics
import com.google.firebase.analytics.ktx.analytics
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.ktx.Firebase

enum class ProviderType {
    BASIC,
    GOOGLE
}


class MainActivity : AppCompatActivity() {



    private lateinit var binding: ActivityMainBinding //Declare binding variable corresponding to activity_main.xml The name of the binding class is generated by converting the name of the XML file to Pascal case and adding the word "Binding" to the end. In this case activity_main.xml --> ActivityMainBinding
    private lateinit var firebaseAnalytics: FirebaseAnalytics
    private val db = FirebaseFirestore.getInstance()


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)


        binding = ActivityMainBinding.inflate(layoutInflater)
        val view = binding.root
        setContentView(view)
        //Analytics Event
        val bottomNavigationBar =
            findViewById<BottomNavigationView>(R.id.bottomNavigationView)//setup fragment with navigation bar
        val navController =
            findNavController(R.id.fragment)//fragment that contains layouts, chronology,plannning, report etc. These fragments are constraint layouts that work like activities


        bottomNavigationBar.setupWithNavController(navController)







//Guardar datos

        //val prefs:SharedPreferences = getSharedPreferences(getString(R.string.prefs_file), Context.MODE_PRIVATE)




//Guardado de datos

       // val prefs = getSharedPreferences(getString(R.string.prefs_file), Context.MODE_PRIVATE)
       // prefs.putString("email", email)


    }

    private fun setup(email: String, provider: String) {

        title="Inicio"

    }
}